-- Phase-1 schema sync: promotions, loyalty tiers, analytics support

CREATE TABLE `promotions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `rule_type` varchar(50) NOT NULL,
  `discount_type` varchar(20) DEFAULT NULL,
  `discount_value` decimal(22,4) DEFAULT NULL,
  `coupon_code` varchar(80) DEFAULT NULL,
  `target_scope` varchar(40) NOT NULL DEFAULT 'all_products',
  `target_id` bigint unsigned DEFAULT NULL,
  `min_order_total` decimal(22,4) DEFAULT NULL,
  `min_qty` decimal(22,4) DEFAULT NULL,
  `max_discount_amount` decimal(22,4) DEFAULT NULL,
  `buy_qty` decimal(22,4) DEFAULT NULL,
  `get_qty` decimal(22,4) DEFAULT NULL,
  `bundle_qty` decimal(22,4) DEFAULT NULL,
  `bundle_price` decimal(22,4) DEFAULT NULL,
  `tier_min_qty` decimal(22,4) DEFAULT NULL,
  `usage_limit_per_coupon` int DEFAULT NULL,
  `usage_limit_per_customer` int DEFAULT NULL,
  `is_active` tinyint NOT NULL DEFAULT 1,
  `priority` int NOT NULL DEFAULT 1,
  `starts_at` timestamp NULL DEFAULT NULL,
  `ends_at` timestamp NULL DEFAULT NULL,
  `notes` text,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `promotions_business_id_index` (`business_id`),
  KEY `promotions_rule_type_index` (`rule_type`),
  KEY `promotions_coupon_code_index` (`coupon_code`),
  KEY `promotions_target_id_index` (`target_id`),
  KEY `promotions_is_active_index` (`is_active`),
  KEY `promotions_priority_index` (`priority`),
  KEY `promotions_starts_at_index` (`starts_at`),
  KEY `promotions_ends_at_index` (`ends_at`),
  KEY `promotions_created_by_foreign` (`created_by`),
  CONSTRAINT `promotions_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `promotions_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `promotion_usages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `promotion_id` bigint unsigned NOT NULL,
  `transaction_id` int unsigned DEFAULT NULL,
  `contact_id` int unsigned DEFAULT NULL,
  `coupon_code` varchar(80) DEFAULT NULL,
  `discount_amount` decimal(22,4) NOT NULL DEFAULT '0.0000',
  `meta` text,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `promotion_usages_business_id_index` (`business_id`),
  KEY `promotion_usages_promotion_id_index` (`promotion_id`),
  KEY `promotion_usages_transaction_id_index` (`transaction_id`),
  KEY `promotion_usages_contact_id_index` (`contact_id`),
  KEY `promotion_usages_coupon_code_index` (`coupon_code`),
  KEY `promotion_usages_created_by_foreign` (`created_by`),
  CONSTRAINT `promotion_usages_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `promotion_usages_contact_id_foreign` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `promotion_usages_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `promotion_usages_promotion_id_foreign` FOREIGN KEY (`promotion_id`) REFERENCES `promotions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `promotion_usages_transaction_id_foreign` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `transactions`
  ADD COLUMN `promotion_code` varchar(80) NULL AFTER `discount_amount`,
  ADD COLUMN `promotion_discount_amount` decimal(22,4) NOT NULL DEFAULT '0.0000' AFTER `promotion_code`,
  ADD COLUMN `promotion_meta` text NULL AFTER `promotion_discount_amount`,
  ADD INDEX `transactions_promotion_code_index` (`promotion_code`);

CREATE TABLE `loyalty_tiers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `level` int NOT NULL DEFAULT 1,
  `min_total_points` decimal(22,4) NOT NULL DEFAULT '0.0000',
  `min_lifetime_sales` decimal(22,4) NOT NULL DEFAULT '0.0000',
  `bonus_multiplier` decimal(12,4) NOT NULL DEFAULT '1.0000',
  `extra_discount_percent` decimal(12,4) NOT NULL DEFAULT '0.0000',
  `is_active` tinyint NOT NULL DEFAULT 1,
  `benefits` text,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loyalty_tiers_business_id_index` (`business_id`),
  KEY `loyalty_tiers_level_index` (`level`),
  KEY `loyalty_tiers_is_active_index` (`is_active`),
  KEY `loyalty_tiers_created_by_foreign` (`created_by`),
  CONSTRAINT `loyalty_tiers_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `loyalty_tiers_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `contacts`
  ADD COLUMN `loyalty_tier_id` bigint unsigned NULL AFTER `customer_group_id`,
  ADD COLUMN `lifetime_sale_total` decimal(22,4) NOT NULL DEFAULT '0.0000' AFTER `total_rp_used`,
  ADD INDEX `contacts_loyalty_tier_id_index` (`loyalty_tier_id`),
  ADD CONSTRAINT `contacts_loyalty_tier_id_foreign` FOREIGN KEY (`loyalty_tier_id`) REFERENCES `loyalty_tiers` (`id`) ON DELETE SET NULL;

CREATE TABLE `loyalty_point_ledgers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `contact_id` int unsigned NOT NULL,
  `transaction_id` int unsigned DEFAULT NULL,
  `entry_type` varchar(30) NOT NULL,
  `points` decimal(22,4) NOT NULL DEFAULT '0.0000',
  `balance_after` decimal(22,4) NOT NULL DEFAULT '0.0000',
  `note` text,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `loyalty_point_ledgers_business_id_index` (`business_id`),
  KEY `loyalty_point_ledgers_contact_id_index` (`contact_id`),
  KEY `loyalty_point_ledgers_transaction_id_index` (`transaction_id`),
  KEY `loyalty_point_ledgers_entry_type_index` (`entry_type`),
  KEY `loyalty_point_ledgers_created_by_foreign` (`created_by`),
  CONSTRAINT `loyalty_point_ledgers_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `loyalty_point_ledgers_contact_id_foreign` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `loyalty_point_ledgers_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `loyalty_point_ledgers_transaction_id_foreign` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
