-- Phase-2 schema sync: ESL and weighing scale real integration tracks

CREATE TABLE `esl_devices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `vendor` varchar(60) NOT NULL DEFAULT 'generic',
  `device_name` varchar(120) NOT NULL,
  `device_identifier` varchar(120) DEFAULT NULL,
  `location_ref` varchar(120) DEFAULT NULL,
  `is_active` tinyint NOT NULL DEFAULT 1,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `esl_devices_business_id_index` (`business_id`),
  KEY `esl_devices_vendor_index` (`vendor`),
  KEY `esl_devices_device_identifier_index` (`device_identifier`),
  KEY `esl_devices_is_active_index` (`is_active`),
  KEY `esl_devices_created_by_foreign` (`created_by`),
  CONSTRAINT `esl_devices_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `esl_devices_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `esl_sync_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `product_id` int unsigned DEFAULT NULL,
  `esl_device_id` bigint unsigned DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `payload` text,
  `response_body` text,
  `error_message` text,
  `synced_at` timestamp NULL DEFAULT NULL,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `esl_sync_logs_business_id_index` (`business_id`),
  KEY `esl_sync_logs_product_id_index` (`product_id`),
  KEY `esl_sync_logs_esl_device_id_index` (`esl_device_id`),
  KEY `esl_sync_logs_status_index` (`status`),
  KEY `esl_sync_logs_synced_at_index` (`synced_at`),
  KEY `esl_sync_logs_created_by_foreign` (`created_by`),
  CONSTRAINT `esl_sync_logs_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `esl_sync_logs_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `esl_sync_logs_esl_device_id_foreign` FOREIGN KEY (`esl_device_id`) REFERENCES `esl_devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `esl_sync_logs_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `scale_devices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `vendor` varchar(60) NOT NULL DEFAULT 'generic',
  `name` varchar(120) NOT NULL,
  `connection_type` varchar(30) NOT NULL DEFAULT 'tcp',
  `host` varchar(150) DEFAULT NULL,
  `port` int DEFAULT NULL,
  `serial_port` varchar(80) DEFAULT NULL,
  `api_url` varchar(255) DEFAULT NULL,
  `api_key` varchar(191) DEFAULT NULL,
  `is_default` tinyint NOT NULL DEFAULT 0,
  `is_active` tinyint NOT NULL DEFAULT 1,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `scale_devices_business_id_index` (`business_id`),
  KEY `scale_devices_vendor_index` (`vendor`),
  KEY `scale_devices_connection_type_index` (`connection_type`),
  KEY `scale_devices_is_active_index` (`is_active`),
  KEY `scale_devices_created_by_foreign` (`created_by`),
  CONSTRAINT `scale_devices_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `scale_devices_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `scale_read_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` int unsigned NOT NULL,
  `scale_device_id` bigint unsigned DEFAULT NULL,
  `weight` decimal(22,6) DEFAULT NULL,
  `unit` varchar(20) DEFAULT NULL,
  `barcode` varchar(64) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'success',
  `response_body` text,
  `error_message` text,
  `created_by` int unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `scale_read_logs_business_id_index` (`business_id`),
  KEY `scale_read_logs_scale_device_id_index` (`scale_device_id`),
  KEY `scale_read_logs_barcode_index` (`barcode`),
  KEY `scale_read_logs_status_index` (`status`),
  KEY `scale_read_logs_created_by_foreign` (`created_by`),
  CONSTRAINT `scale_read_logs_business_id_foreign` FOREIGN KEY (`business_id`) REFERENCES `business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `scale_read_logs_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `scale_read_logs_scale_device_id_foreign` FOREIGN KEY (`scale_device_id`) REFERENCES `scale_devices` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
